### PR TITLE
Adding code to run on Powersystem

### PR DESCRIPTION
**Pull request by genisysram**
Hi
Here is my contribution to your code, its working good on powersystems.

Thanks for the code, its working good.
## What do these changes do?
Added Architecture "ppc64le"
## Are there changes in behavior for the user?
No

### CODE REVIEW

**Comment by genisysram** [comment]
@johnweldon
Please merge my PR

**Comment by johnweldon** [comment]
> @johnweldon
> Please merge my PR

Hi @genisysram - thanks for contributing; I'm not clear on the benefits of this change, can you tell me why you want it merged?

**Comment by genisysram** [comment]
This also ensures that whatever versions of go you are using is complete and supports all features on ppc64le. And, it is possible for go programs to be architecture dependent - if someone ever adds a dependency on the hardware, expected or not, this will ensure that the project will always build when it gets to the distros - if not, the distro porting team winds up picking up the work which can be painful to those coming in from outside the project.

**Review by johnweldon — APPROVED** [review]

**Comment by johnweldon** [comment]
Thank you @genisysram

**Pull request merged**
