### PR TITLE
Skip 64-bit tests on 32-bit platforms

### LINKED ISSUE #5: tests fail on armhf
Hello,

The Debian CI found that tests are failing on armhf, it looks like a simple bug:

```
src/gopkg.in/asn1-ber.v1/length_test.go:83: constant 9223372036854775807 overflows int
src/gopkg.in/asn1-ber.v1/length_test.go:137: constant 9223372036854775807 overflows int
```

Detailed logs: https://reproducible.debian.net/rb-pkg/unstable/armhf/golang-gopkg-asn1-ber.v1.html

### LINKED ISSUE #6: The maximum value for an int type
Hi!
The following program crashes on x86 architecture:

[   82s] ../go/src/gopkg.in/asn1-ber.v1/length_test.go:83: constant 9223372036854775807 overflows int
[   82s] ../go/src/gopkg.in/asn1-ber.v1/length_test.go:137: constant 9223372036854775807 overflows int

See: https://build.opensuse.org/build/home:awissu:branches:devel:languages:go/openSUSE_Tumbleweed/i586/golang-gopkgin-asn1-ber/_log

### PR DESCRIPTION
**Pull request by liggitt**
fixes #5 
fixes #6

also ensures overflow is correctly detected on 32-bit platforms

### CODE REVIEW

**Comment by dlzr** [comment]
This worked for fixing the failure in TestReadLength, but TestEncodeLength had a similar failure on 32-bit arches.  I've sent #12 with a suggested fix (and I'm trying to get the patch included in the next Debian release).

**Comment by liggitt** [comment]
thanks, I actually had something similar in progress... I updated this with fixes and added tests for max lengths on 32-bit platforms

**Comment by liggitt** [comment]
@dlzr can you let me know if the latest version works for you

@johnweldon, any comments?

**Comment by dlzr** [comment]
@liggitt the latest version of your changes (c25d657) also fixes the debian bug (the test changes are almost identical to #12).  Since I'm trying to fix release-critical bugs, I tried to keep the patch minimal, that's why I only touched the test file in my version.

**Pull request merged**
