### PR TITLE
add encoding / parsing of real values

### PR DESCRIPTION
**Pull request by vetinari**
This does not cover all test cases from the suite. TC8 returns an error instead of a warning, but I think that's ok.

### CODE REVIEW

**Comment by liggitt** [comment]
> This does not cover all test cases from the suite. TC8 returns an error instead of a warning, but I think that's ok.

was the suite faulty, or was there a compelling reason not to support the type uniformly?

**Comment by vetinari** [comment]
Wasn't clear what the errors from the suite were. Fixed now.

**Comment by johnweldon** [comment]
Try rebasing on master

**Comment by vetinari** [comment]
merged w/ current master

**Comment by s00500** [comment]
I am trying to use this library for ember. running on a 64bit os... and the results I get from the real parsing are strangely wrong. I have reimplemented the exact style used here... but I am not sure if it is different from what this library tries to achieve....

https://github.com/Lawo/ember-plus-sharp/blob/78e3cd816e699f3fe6b7a94db9668397398ec437/Lawo.EmberPlusSharp/Ember/EmberWriter.cs

Any Inputs ? I can get my code into a pr at some point, for now I am fine using the Bytes() function and continue with custom parsing....

**Comment by s00500** [comment]
EG:
Bytes: 09 03 c0 04 05 

Parse as -80.0

While I expect them to parse as -20....

**Comment by vetinari** [comment]
Can you explain how you get to `-20`? 

The contents of tests/tc10.ber (0x09, 0x07, 0x83, 0x04, 0xff, 0xff, 0xff, 0xfb, 0x05) parse correctly as 0.156250 with 
```go
func TestRealDecoding(t *testing.T) {
    dec, err := DecodePacketErr([]byte{0x09, 0x07, 0x83, 0x04, 0xff, 0xff, 0xff, 0xfb, 0x05})
    if err != nil {
        t.Errorf("Failed to decode: %s", err)
    }
    if dec.Value.(float64) != 0.156250 {
        t.Errorf("invalid value parsed in tc10: %f <=> 0.156250", dec.Value.(float64))
    }
}
```

so the algorythm to decode the binary encoding should be correct.

**Pull request merged**
