### PR TITLE
Use MaxInt32 to avoid overflow on non-64 bit CPU's

### LINKED ISSUE #5: tests fail on armhf
Hello,

The Debian CI found that tests are failing on armhf, it looks like a simple bug:

```
src/gopkg.in/asn1-ber.v1/length_test.go:83: constant 9223372036854775807 overflows int
src/gopkg.in/asn1-ber.v1/length_test.go:137: constant 9223372036854775807 overflows int
```

Detailed logs: https://reproducible.debian.net/rb-pkg/unstable/armhf/golang-gopkg-asn1-ber.v1.html

### LINKED ISSUE #6: The maximum value for an int type
Hi!
The following program crashes on x86 architecture:

[   82s] ../go/src/gopkg.in/asn1-ber.v1/length_test.go:83: constant 9223372036854775807 overflows int
[   82s] ../go/src/gopkg.in/asn1-ber.v1/length_test.go:137: constant 9223372036854775807 overflows int

See: https://build.opensuse.org/build/home:awissu:branches:devel:languages:go/openSUSE_Tumbleweed/i586/golang-gopkgin-asn1-ber/_log

### PR DESCRIPTION
**Pull request by johnweldon**
Resolves #5 and Resolves #6

### CODE REVIEW

**Comment by liggitt** [comment]
I wish there was a way to preserve the int64 test. Declaring the test struct expected value as an int64 doesn't help, does it?

**Comment by johnweldon** [comment]
I was thinking of adding a length_test_amd64.go or using +build flags to enable the 64 bit version when the hardware supports it.

**Comment by liggitt** [comment]
https://github.com/go-asn1-ber/asn1-ber/pull/11 is an alternative that just skips the test on non-64-bit platforms

**Comment by liggitt** [comment]
fixed in #11

**Pull request closed without merging**
